### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by spacemonqi** [EMBEDDIA/bert-bilstm-cnn-crf-ner#3]
Hi @creat89, @jgmorenof 

Using all the package versions as given in the environment.yml file with Python 3.6.13, running 

`python3.6 NER.py -f input.txt -F plain -l en -o output.txt`

yields:

Using TensorFlow backend.
File to process: input.conll
Language to process: en
Output redirected to: {'output.txt'}
Using CPU
trap: SIGINT: bad trap
Traceback (most recent call last):
  File "NER.py", line 352, in <module>
    main_command()
  File "NER.py", line 65, in main_command
    lstm_model = loadModels(arguments.language)
  File "NER.py", line 164, in loadModels
    subprocess.run(["sh", "./embeddings/komninos_embeddings.sh"], check=True)
  File "/home/daniel/anaconda3/envs/bert_env/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', './embeddings/komninos_embeddings.sh']' returned non-zero exit status 1.

**Comment by Teslassian** [comment]
Apologies, it is of course in the .yml.

**Comment by creat89** [comment]
Dear @Teslassian,

I will check the code ASAP. But in the meantime, can you tell me if you trained your own English model? Otherwise, I am seeing that the current repository doesn't contain an English model.
